require(here)
png(filename = here("basic_histogram.png"), width = 800, height = 600)
boxplot(penguins$body_mass_g)
dev.off()
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
require(here)
png(filename = here("coplotpenguins.png"), width = 800, height = 600)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
dev.off()
here
here()
install.packages("here")
here()
require(here)
png(filename = here("coplotpenguins.png"), width = 800, height = 600)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
dev.off()
require(here)
require(here)
png(filename = here("coplotpenguins.png"), width = 800, height = 600)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
dev.off()
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
require(here)
png(filename = here("coplotpenguins2.png"), width = 800, height = 600)
coplot(body_mass_g ~ bill_depth_mm | sex, data = penguins)
dev.off()
require(here)
png(filename = here("boxplotpenguins.png"), width = 800, height = 600)
boxplot(bill_depth_mm ~ sex, data = penguins)
dev.off()
boxplot(bill_depth_mm ~ sex, data = penguins)
require(here)
png(filename = here("boxplotpenguins2.png"), width = 800, height = 600)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
dev.off()
